config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'user/index'
  root to: 'user#index'

  get 'events/new', to: 'events#new', as: 'events_new'
  get 'events/:id', to: 'events#show', as: 'events_show'

  post 'events/new', to: 'events#create', as: 'events_create'

  post 'events/subscribe', to: 'events#subscribe', as: 'events_subscribe'

  get 'events/edit/:id', to: 'events#edit', as: 'events_edit'
  post 'events/edit/:id', to: 'events#modify', as: 'modify'

  get '/all', to: 'events#index', as: 'all'

  get '/delete', to: 'events#delete', as: 'delete_events'
  delete '/destroy', to: 'events#destroy', as: 'destroy_events'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def subscribe

    # Amount in cents
  @amount = 1000

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'eur'
  )



  flash[:success] = "Vous participez à l'événement !"
  redirect_to @event
  

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to @event
  end
end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :place, :description)
    end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h2>Créer un Event</h2>

  <div class="field">
    <%= form.label :date %><br />
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :place %><br />
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description %>
  </div>

  <div class="field"><br />
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Place</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.place %></td>
        <td><%= event.description %></td>
        <td><%= event.id %></td>

        <%= form_tag events_subscribe_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">

    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-currency="eur"
          data-amount="1000"
          data-locale="auto"></script>
<% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<p class="text-center">
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p class="text-center">
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p class="text-center">
  <strong>Description:</strong>
  <%= @event.description %>
</p>



<p class="text-center">
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Destroy', destroy_events_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'All Events',  all_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Even</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
     <a class="navbar-brand" href="#">Evenbright</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
           <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="<%= all_path %> ">Tout les Events</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="<%= events_new_path %> ">Créer un Event</a>
         </li>
       </ul>
         <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>

           <% else %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_session_path %>">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
              </li>
          <% end %>


       </ul>
     </div>
   </nav>

    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<br>
<br>
<br>
<h1 class="text-center">Bienvenue</h1>
<h2 class="text-center">Tu aimes les Events? Tu veux des Events? <br>
  Alors connectes toi et rejoins nous dans notre monde fabuleux!</h2>